# -*- mode: shell-script -*-
# ~/.bash_profile: executed by bash(1) for login shells.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# include .bashrc if it exists
#if [ -f ~/.bashrc ]; then
#    . ~/.bashrc
#fi

# make sure that /usr/local/bin is before /usr/bin
if [ -d /usr/local/bin ] ; then
    export PATH=/usr/local/bin:"${PATH}"
fi

# set PATH so it includes user's private bin if it exists
if [ -d ~/bin ] ; then
    export PATH=~/bin:"${PATH}"
fi

# do the same with MANPATH
#if [ -d ~/man ]; then
#    MANPATH=~/man:"${MANPATH}"
#    export MANPATH
#fi

if [ $(uname -s) = "Darwin" ]; then
    if [ -f $(brew --prefix)/etc/bash_completion ]; then
        source $(brew --prefix)/etc/bash_completion
    fi
    if [ -x $(brew --prefix)/etc/bash_completion.d ]; then
        for c in $(brew --prefix)/etc/bash_completion.d/*; do
            source $c
        done
    fi

    source ~/.bashrc
fi
